"""empty message

Revision ID: 2de73e041d2f
Revises: 9e1450df6c23
Create Date: 2025-11-23 11:14:51.421560

"""
from typing import Sequence, Union

import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa
from celery.app.base import USING_EXECV
from cryptography.hazmat.decrepit.ciphers.algorithms import CAST5

# revision identifiers, used by Alembic.
revision: str = '2de73e041d2f'
down_revision: Union[str, Sequence[str], None] = '9e1450df6c23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=30),
               type_=sqlalchemy_utils.types.password.PasswordType(
            max_length=1137
        ),
               existing_nullable=False,
                    postgresql_using='password::bytea'
                    ),

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.LargeBinary(),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    # ### end Alembic commands ###
