"""empty message

Revision ID: 428da12d3edf
Revises: ee9fdd8d7771
Create Date: 2025-11-12 14:36:05.742338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '428da12d3edf'
down_revision: Union[str, Sequence[str], None] = 'ee9fdd8d7771'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('name', sa.String(length=30), nullable=True))
    op.add_column('products', sa.Column('price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'price')
    op.drop_column('products', 'name')
    # ### end Alembic commands ###
