"""empty message

Revision ID: 62551a6b4d95
Revises: 6a3e9c00a260
Create Date: 2025-11-13 13:43:24.170126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62551a6b4d95'
down_revision: Union[str, Sequence[str], None] = '6a3e9c00a260'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    None
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    None
    # ### end Alembic commands ###
