"""empty message

Revision ID: 6ed84b26c0c9
Revises: 428da12d3edf
Create Date: 2025-11-12 14:38:48.478143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ed84b26c0c9'
down_revision: Union[str, Sequence[str], None] = '428da12d3edf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('desription', sa.String(length=30), nullable=True))
    op.alter_column('products', 'name',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'name',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.drop_column('products', 'desription')
    # ### end Alembic commands ###
