"""empty message

Revision ID: 8e649569988c
Revises: 1e5338e52983
Create Date: 2025-11-16 12:47:42.059579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e649569988c'
down_revision: Union[str, Sequence[str], None] = '1e5338e52983'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipments', sa.Column('category', sa.String(length=30), nullable=False))
    op.add_column('users', sa.Column('password', sa.String(length=30), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    op.drop_column('equipments', 'category')
    # ### end Alembic commands ###
