"""change price column type from String to Integer

Revision ID: 9e1450df6c23
Revises: a2ee8181795e
Create Date: 2025-11-17 12:35:39.880235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e1450df6c23'
down_revision: Union[str, Sequence[str], None] = 'a2ee8181795e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipments', sa.Column('price', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('equipments', 'price')
    # ### end Alembic commands ###
